name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VM_KEY }}

    - name: Check network connectivity
      run: |
        ping -c 4 ${{ secrets.VM_HOST }}

    - name: Test SSH Connection
      run: |
        ssh -v ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "echo 'SSH connection successful'"
      shell: bash

    - name: Deploy to VMware using Run Command
      run: |
        ssh -v ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd C:\\inetpub\\wwwroot\\NetCore7 && git pull origin main && dotnet build --configuration Release && dotnet publish --configuration Release --output C:\\inetpub\\wwwroot\\NetCore7"
      shell: bash
