name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    - name: Install Git
      run: |
        choco install git -y  
        refreshenv  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        port: 22  # Cổng mặc định của SSH
        script: |
          cd C:\inetpub\wwwroot\NetCore7  
          git pull origin main  
          dotnet build --configuration Release  
          dotnet publish --configuration Release --output ./publish  

      env:
        DOTNET_ROOT: C:\Program Files\dotnet
