name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build
      
    - name: Deploy to Windows Server
      env:
        WIN_SERVER_HOST: ${{ secrets.VM_HOST }}
        WIN_SERVER_USER: ${{ secrets.VM_USER }}
        WIN_SERVER_SSH_PRIVATE_KEY: ${{ secrets.VM_KEY }}  
        WIN_SERVER_PORT: 22
        DOTNET_ROOT: 'C:\Program Files\dotnet'

      shell: pwsh  

      run: |
        $ErrorActionPreference = 'Stop'
        $env:DOTNET_ROOT = 'C:\Program Files\dotnet'

      
        $keyContent = $env:WIN_SERVER_SSH_PRIVATE_KEY
        $keyPath = "$env:USERPROFILE\id_rsa"  
        $keyContent | Out-File -FilePath $keyPath -Encoding UTF8

        ssh -i "$keyPath" $env:WIN_SERVER_USER@$env:WIN_SERVER_HOST `
          -p $env:WIN_SERVER_PORT `
          "cd C:\inetpub\wwwroot\NetCore7; `
          git pull origin main; `
          dotnet build --configuration Release; `
          dotnet publish --configuration Release --output ./publish"
